
import "./globals.css";

import SiteNavigation from "@/components/SiteNavigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SiteNavigation />
        <main>{children}</main>
      </body>
    </html>
  );
}
